Repository auth0/SimpleKeychain, pull requests merged in 2020-02, with the labels that each got.

#76 Release 0.10.0 [SDK-1343]
  CHANGELOG.md
  README.md
  SimpleKeychain/Info.plist
  SimpleKeychainApp/Info.plist
  SimpleKeychainTests/Info.plist
  fastlane/README.md
Labels: small

#80 Generate code coverage report [SDK-1344]
  README.md
  SimpleKeychain.xcodeproj/xcshareddata/xcschemes/SimpleKeychain-iOS.xcscheme
Labels: tiny

#82 Fixed tvOS tests
  SimpleKeychain.xcodeproj/project.pbxproj
  tvOSTestHost/AppDelegate.swift
  tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Contents.json
  tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Contents.json
  tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Contents.json
  tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Contents.json
  tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Contents.json
  tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Contents.json
  tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Contents.json
  tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Contents.json
  tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Contents.json
  tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image Wide.imageset/Contents.json
  tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image.imageset/Contents.json
  tvOSTestHost/Assets.xcassets/Contents.json
  tvOSTestHost/Base.lproj/LaunchScreen.storyboard
  tvOSTestHost/Base.lproj/Main.storyboard
  tvOSTestHost/Info.plist
  tvOSTestHost/ViewController.swift
  tvOSTestHost/tvOSTestHost.entitlements
Labels: medium

#86 Mark up A0SimpleKeychain+KeyPair to admit that keys may not exist
  SimpleKeychain/A0SimpleKeychain+KeyPair.h
Labels: CH: Changed, tiny

#83 Updated CI config [SDK-1356]
  .circleci/config.yml
  .slather.yml
  Gemfile
  Gemfile.lock
  SimpleKeychain.xcodeproj/project.pbxproj
  SimpleKeychain.xcodeproj/xcshareddata/xcschemes/SimpleKeychain-iOS.xcscheme
Labels: small

#81 Fixed A0LocalAuthenticationCapable macro
  SimpleKeychain/A0SimpleKeychain.h
Labels: CH: Fixed, tiny

#87 Release 0.11.0
  CHANGELOG.md
  README.md
  SimpleKeychain/Info.plist
  SimpleKeychainApp/Info.plist
  SimpleKeychainTests/Info.plist
  tvOSTestHost/Info.plist
Labels: small
