Repository auth0/SimpleKeychain, pull requests merged in 2022-06, with the labels that each got.

#127 Add migration guide [SDK-3393]
  V1_MIGRATION_GUIDE.md
Labels: documentation, review:tiny

#126 Remove license header from source files [SDK-3389]
  SimpleKeychain/A0SimpleKeychain+KeyPair.h
  SimpleKeychain/A0SimpleKeychain+KeyPair.m
  SimpleKeychain/A0SimpleKeychain.h
  SimpleKeychain/A0SimpleKeychain.m
  SimpleKeychain/SimpleKeychain.h
  SimpleKeychainApp/AppDelegate.swift
  SimpleKeychainTests/SimpleKeychainSpec.swift
  tvOSTestHost/AppDelegate.swift
  tvOSTestHost/ViewController.swift
Labels: review:tiny

#128 Update year in license file
  LICENSE
Labels: review:tiny

#131 Add `.swiftpm` directory to `.gitignore`
  .gitignore
  .swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
Labels: review:tiny

#130 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, review:tiny

#129 Drop old platform versions [SDK-3387]
  Package.swift
  SimpleKeychain.podspec
  SimpleKeychain.xcodeproj/project.pbxproj
  SimpleKeychain/A0SimpleKeychain.h
  SimpleKeychain/A0SimpleKeychain.m
  V1_MIGRATION_GUIDE.md
Labels: review:small

#135 Update README [SDK-3416]
  README.md
Labels: review:small

#132 Remove deprecated method [SDK-3413]
  SimpleKeychain/A0SimpleKeychain+KeyPair.h
  SimpleKeychain/A0SimpleKeychain+KeyPair.m
  V1_MIGRATION_GUIDE.md
Labels: review:tiny

#133 Remove usage of deprecated properties [SDK-3414]
  SimpleKeychain/A0SimpleKeychain.h
  SimpleKeychain/A0SimpleKeychain.m
  V1_MIGRATION_GUIDE.md
Labels: review:tiny

#138 Add support policy [SDK-3420]
  README.md
Labels: documentation, review:small

#136 Remove obsolete functionality [SDK-3419]
  SimpleKeychain.xcodeproj/project.pbxproj
  SimpleKeychain/A0SimpleKeychain+KeyPair.h
  SimpleKeychain/A0SimpleKeychain+KeyPair.m
  SimpleKeychain/SimpleKeychain.h
  SimpleKeychain/include/A0SimpleKeychain+KeyPair.h
  SimpleKeychainTests/SimpleKeychainSpec.swift
  V1_MIGRATION_GUIDE.md
Labels: review:tiny

#140 [SDK-3434] Update issues templates
  .github/ISSUE_TEMPLATE/Bug Report.yml
  .github/ISSUE_TEMPLATE/Feature Request.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/report-a-bug.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: review:small

#139 Migrate to Swift [SDK-3428]
  .circleci/config.yml
  .swiftlint.yml
  README.md
  SimpleKeychain.podspec
  SimpleKeychain.xcodeproj/project.pbxproj
  SimpleKeychain/A0SimpleKeychain.h
  SimpleKeychain/A0SimpleKeychain.m
  SimpleKeychain/Accessibility.swift
  SimpleKeychain/SimpleKeychain.h
  SimpleKeychain/SimpleKeychain.swift
  SimpleKeychain/SimpleKeychainError.swift
  SimpleKeychain/include/A0SimpleKeychain.h
  SimpleKeychainTests/SimpleKeychainErrorSpec.swift
  SimpleKeychainTests/SimpleKeychainSpec.swift
  V1_MIGRATION_GUIDE.md
Labels: review:large

#141 Drop support for old Swift versions [SDK-3444]
  Package.swift
  SimpleKeychain.podspec
  V1_MIGRATION_GUIDE.md
Labels: review:tiny

#142 Add missing unit tests
  SimpleKeychain.xcodeproj/project.pbxproj
  SimpleKeychain/Accessibility.swift
  SimpleKeychain/SimpleKeychain.swift
  SimpleKeychain/SimpleKeychainError.swift
  SimpleKeychainTests/AccessibilitySpec.swift
  SimpleKeychainTests/SimpleKeychainErrorSpec.swift
  SimpleKeychainTests/SimpleKeychainSpec.swift
Labels: review:large

#143 Apply recommended Xcode 14 settings
  SimpleKeychain.xcodeproj/project.pbxproj
  SimpleKeychain.xcodeproj/xcshareddata/xcschemes/SimpleKeychain-OSX.xcscheme
  SimpleKeychain.xcodeproj/xcshareddata/xcschemes/SimpleKeychain-iOS.xcscheme
  SimpleKeychain.xcodeproj/xcshareddata/xcschemes/SimpleKeychain-tvOS.xcscheme
  SimpleKeychain.xcodeproj/xcshareddata/xcschemes/SimpleKeychain-watchOS.xcscheme
  SimpleKeychain.xcodeproj/xcshareddata/xcschemes/SimpleKeychainApp.xcscheme
  SimpleKeychainTests/SimpleKeychainErrorSpec.swift
  SimpleKeychainTests/SimpleKeychainSpec.swift
Labels: review:small

#144 [SDK-3450] API Documentation Generation
  .gitignore
  .shiprc
  Gemfile.lock
  fastlane/Fastfile
  fastlane/README.md
Labels: documentation, review:tiny

#146 Add support for iCloud synchronization
  SimpleKeychain/SimpleKeychain.swift
  SimpleKeychainTests/SimpleKeychainSpec.swift
Labels: review:small

#147 Add unit tests for queries
  SimpleKeychain/SimpleKeychain.swift
  SimpleKeychainTests/SimpleKeychainSpec.swift
Labels: review:small

#148 Improve API docs generation
  fastlane/Fastfile
Labels: review:small

#152 Re-generate API docs
  docs/data/documentation/simplekeychain.json
  docs/data/documentation/simplekeychain/accessibility.json
  docs/data/documentation/simplekeychain/accessibility/!=(_:_:).json
  docs/data/documentation/simplekeychain/accessibility/afterfirstunlock.json
  docs/data/documentation/simplekeychain/accessibility/afterfirstunlockthisdeviceonly.json
  docs/data/documentation/simplekeychain/accessibility/equatable-implementations.json
  docs/data/documentation/simplekeychain/accessibility/hash(into:).json
  docs/data/documentation/simplekeychain/accessibility/init(rawvalue:).json
  docs/data/documentation/simplekeychain/accessibility/rawrepresentable-implementations.json
  docs/data/documentation/simplekeychain/accessibility/rawvalue.json
  docs/data/documentation/simplekeychain/accessibility/whenpasscodesetthisdeviceonly.json
  docs/data/documentation/simplekeychain/accessibility/whenunlocked.json
  docs/data/documentation/simplekeychain/accessibility/whenunlockedthisdeviceonly.json
  docs/data/documentation/simplekeychain/simplekeychain.json
  docs/data/documentation/simplekeychain/simplekeychain/data(forkey:).json
  docs/data/documentation/simplekeychain/simplekeychain/deleteall().json
  docs/data/documentation/simplekeychain/simplekeychain/deleteitem(forkey:).json
  docs/data/documentation/simplekeychain/simplekeychain/hasitem(forkey:).json
  docs/data/documentation/simplekeychain/simplekeychain/init(service:accessgroup:accessibility:accesscontrolflags:context:).json
  docs/data/documentation/simplekeychain/simplekeychain/init(service:accessgroup:accessibility:accesscontrolflags:context:synchronizable:).json
  docs/data/documentation/simplekeychain/simplekeychain/keys().json
  docs/data/documentation/simplekeychain/simplekeychain/set(_:forkey:)-618u7.json
  docs/data/documentation/simplekeychain/simplekeychain/set(_:forkey:)-n98i.json
  docs/data/documentation/simplekeychain/simplekeychain/string(forkey:).json
  docs/data/documentation/simplekeychain/simplekeychainerror.json
  docs/data/documentation/simplekeychain/simplekeychainerror/!=(_:_:).json
  docs/data/documentation/simplekeychain/simplekeychainerror/==(_:_:).json
  docs/data/documentation/simplekeychain/simplekeychainerror/authfailed.json
  docs/data/documentation/simplekeychain/simplekeychainerror/debugdescription.json
  docs/data/documentation/simplekeychain/simplekeychainerror/decodefailed.json
  docs/data/documentation/simplekeychain/simplekeychainerror/duplicateitem.json
  docs/data/documentation/simplekeychain/simplekeychainerror/equatable-implementations.json
  docs/data/documentation/simplekeychain/simplekeychainerror/error-implementations.json
  docs/data/documentation/simplekeychain/simplekeychainerror/errordescription-23ktd.json
  docs/data/documentation/simplekeychain/simplekeychainerror/errordescription-31jbz.json
  docs/data/documentation/simplekeychain/simplekeychainerror/failurereason.json
  docs/data/documentation/simplekeychain/simplekeychainerror/helpanchor.json
  docs/data/documentation/simplekeychain/simplekeychainerror/interactionnotallowed.json
  docs/data/documentation/simplekeychain/simplekeychainerror/invalidparameters.json
  docs/data/documentation/simplekeychain/simplekeychainerror/itemnotavailable.json
  docs/data/documentation/simplekeychain/simplekeychainerror/itemnotfound.json
  docs/data/documentation/simplekeychain/simplekeychainerror/localizeddescription-2xh78.json
  docs/data/documentation/simplekeychain/simplekeychainerror/localizeddescription-6p7yv.json
  docs/data/documentation/simplekeychain/simplekeychainerror/localizederror-implementations.json
  docs/data/documentation/simplekeychain/simplekeychainerror/operationnotimplemented.json
  docs/data/documentation/simplekeychain/simplekeychainerror/other.json
  docs/data/documentation/simplekeychain/simplekeychainerror/recoverysuggestion.json
  docs/data/documentation/simplekeychain/simplekeychainerror/status.json
  docs/data/documentation/simplekeychain/simplekeychainerror/unknown.json
  docs/data/documentation/simplekeychain/simplekeychainerror/usercanceled.json
  docs/data/documentation/simplekeychain/simplekeychainerror/~=(_:_:)-7uptb.json
  docs/documentation/simplekeychain/simplekeychain/init(service:accessgroup:accessibility:accesscontrolflags:context:synchronizable:)/index.html
  docs/index.html
  docs/index/data.mdb
  docs/index/index.json
  docs/index/navigator.index
Labels: review:tiny

#153 Add support for custom attributes
  README.md
  SimpleKeychain/SimpleKeychain.swift
  SimpleKeychain/SimpleKeychainError.swift
  SimpleKeychainTests/SimpleKeychainSpec.swift
  V1_MIGRATION_GUIDE.md
Labels: review:small

#154 Replace OSX with macOS in schemes and targets
  .circleci/config.yml
  SimpleKeychain.xcodeproj/project.pbxproj
  SimpleKeychain.xcodeproj/xcshareddata/xcschemes/SimpleKeychain-macOS.xcscheme
Labels: review:small

#158 Fix 'access group' capitalization
  README.md
  SimpleKeychain.podspec
  SimpleKeychain/SimpleKeychain.swift
Labels: review:tiny

#159 Update API docs
  docs/data/documentation/simplekeychain.json
  docs/data/documentation/simplekeychain/accessibility.json
  docs/data/documentation/simplekeychain/accessibility/!=(_:_:).json
  docs/data/documentation/simplekeychain/accessibility/afterfirstunlock.json
  docs/data/documentation/simplekeychain/accessibility/afterfirstunlockthisdeviceonly.json
  docs/data/documentation/simplekeychain/accessibility/equatable-implementations.json
  docs/data/documentation/simplekeychain/accessibility/hash(into:).json
  docs/data/documentation/simplekeychain/accessibility/hashvalue.json
  docs/data/documentation/simplekeychain/accessibility/init(rawvalue:).json
  docs/data/documentation/simplekeychain/accessibility/rawrepresentable-implementations.json
  docs/data/documentation/simplekeychain/accessibility/rawvalue.json
  docs/data/documentation/simplekeychain/accessibility/whenpasscodesetthisdeviceonly.json
  docs/data/documentation/simplekeychain/accessibility/whenunlocked.json
  docs/data/documentation/simplekeychain/accessibility/whenunlockedthisdeviceonly.json
  docs/data/documentation/simplekeychain/simplekeychain.json
  docs/data/documentation/simplekeychain/simplekeychain/data(forkey:).json
  docs/data/documentation/simplekeychain/simplekeychain/deleteall().json
  docs/data/documentation/simplekeychain/simplekeychain/deleteitem(forkey:).json
  docs/data/documentation/simplekeychain/simplekeychain/hasitem(forkey:).json
  docs/data/documentation/simplekeychain/simplekeychain/init(service:accessgroup:accessibility:accesscontrolflags:context:synchronizable:attributes:).json
  docs/data/documentation/simplekeychain/simplekeychain/keys().json
  docs/data/documentation/simplekeychain/simplekeychain/set(_:forkey:)-618u7.json
  docs/data/documentation/simplekeychain/simplekeychain/set(_:forkey:)-n98i.json
  docs/data/documentation/simplekeychain/simplekeychain/string(forkey:).json
  docs/data/documentation/simplekeychain/simplekeychainerror.json
  docs/data/documentation/simplekeychain/simplekeychainerror/!=(_:_:).json
  docs/data/documentation/simplekeychain/simplekeychainerror/==(_:_:).json
  docs/data/documentation/simplekeychain/simplekeychainerror/authfailed.json
  docs/data/documentation/simplekeychain/simplekeychainerror/debugdescription.json
  docs/data/documentation/simplekeychain/simplekeychainerror/decodefailed.json
  docs/data/documentation/simplekeychain/simplekeychainerror/duplicateitem.json
  docs/data/documentation/simplekeychain/simplekeychainerror/equatable-implementations.json
  docs/data/documentation/simplekeychain/simplekeychainerror/error-implementations.json
  docs/data/documentation/simplekeychain/simplekeychainerror/errordescription-23ktd.json
  docs/data/documentation/simplekeychain/simplekeychainerror/errordescription-31jbz.json
  docs/data/documentation/simplekeychain/simplekeychainerror/failurereason.json
  docs/data/documentation/simplekeychain/simplekeychainerror/helpanchor.json
  docs/data/documentation/simplekeychain/simplekeychainerror/interactionnotallowed.json
  docs/data/documentation/simplekeychain/simplekeychainerror/invalidparameters.json
  docs/data/documentation/simplekeychain/simplekeychainerror/itemnotavailable.json
  docs/data/documentation/simplekeychain/simplekeychainerror/itemnotfound.json
  docs/data/documentation/simplekeychain/simplekeychainerror/localizeddescription-2xh78.json
  docs/data/documentation/simplekeychain/simplekeychainerror/localizederror-implementations.json
  docs/data/documentation/simplekeychain/simplekeychainerror/operationnotimplemented.json
  docs/data/documentation/simplekeychain/simplekeychainerror/recoverysuggestion.json
  docs/data/documentation/simplekeychain/simplekeychainerror/status.json
  docs/data/documentation/simplekeychain/simplekeychainerror/unknown.json
  docs/data/documentation/simplekeychain/simplekeychainerror/usercanceled.json
  docs/data/documentation/simplekeychain/simplekeychainerror/~=(_:_:)-41lv0.json
  docs/data/documentation/simplekeychain/simplekeychainerror/~=(_:_:)-7uptb.json
Labels: review:tiny
